import Head from "next/head";
import Navbar from "@/components/Navbar";
import LeftSide from "@/components/LeftSide";

export default function Home() {
  return (
    <>
      <Head>
        <title>Nodnyl Perez</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale-1" />
        <link rel="icon" href="favicon.ico" />
      </Head>
      <main className="w-full h-screen font-bodyfont bg-bodyColor text-textLight overflow-x-hidden overflow-y-scroll">
        <Navbar />
        <div className="w-full h-[88vh] xl:flex items-center gap-20 justify-between">
          <div className="hidden xl:inline-flex w-32 h-full fixed left-0 bottom-0">
            <LeftSide />
          </div>
          <div>Middle</div>
          <div></div>
        </div>
      </main>
    </>
  );
}
